[versions]
assertj = "3.23.1"
gson = "2.10"
jackson = "2.14.0"
junit = "5.9.1"
mockito = "4.8.1"
moshi = "1.14.0"
wiremock = "2.35.0"

[libraries]
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
jackson = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
mockito-inline = { module = "org.mockito:mockito-inline", version.ref = "mockito" }
mockito-junit = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-adapters = { module = "com.squareup.moshi:moshi-adapters", version.ref = "moshi" }
wiremock = { module = "com.github.tomakehurst:wiremock-jre8", version.ref = "wiremock" }

[bundles]
mockito = [
    "mockito-inline",
    "mockito-junit",
]
moshi = [
    "moshi",
    "moshi-adapters",
]

[plugins]
version-catalog-update = "nl.littlerobots.version-catalog-update:0.7.0"
versions = "com.github.ben-manes.versions:0.43.0"
